### PR TITLE
Alternate output file name for generated files

### PR DESCRIPTION
**Pull request by Jissai**
In grammar file directives @Scanner, @Parser, @ParserTree, @TextHighlighter
now accept the option FileName=&lt;file_name&gt;
Where &lt;file_name&gt; is the name of the file to be generated. &lt;file_name&gt;
must include the extension (ex .cs / .vb)

### CODE REVIEW

**Comment by Jissai** [comment]
I made modification on sourcecode from codeproject v1.3 of tinyPG.
I see there are changes in GitHub but i don't know if they are more recent or not.
I will rework the code to start from github sources

**Comment by tomspilman** [comment]
Hi Jissai.

First thanks for the contribution!

This is an "unofficial" fork of TinyPG (I also posted to your question on CodeProject).  I created it because we had a need for some new features (mainly case insensitive symbols) and was frustrated by the author ignoring my questions.

I decided it would be best to have public fork of TinyPG on GitHub that we could improve and share with others.

> I see there are changes in GitHub but i don't know if they are more recent or not.

We forked from the 1.3 sources originally some months ago:

https://github.com/SickheadGames/TinyPG/tree/7a4ad9681ba047d4bda03978580d081aa0f9454e

... but we've added new features to the code since then.  Those are most likely the differences you are seeing.

**Comment by tomspilman** [comment]
From looking thru this diff the differences you are seeing are from these fixes/features:
- ParseError now properly initializes file and line number information.
- Production rules without a code block will by default evaluate their sub-rules.
- IDE now uses C# 3.x compiler when testing the generated parser code.
- Support for `[IgnoreCase]` flag on terminal symbols.
- New `[FileAndLine]` attribute for redefining the file and line number reported in errors.

This is all new code that didn't exist in 1.3.

**Comment by Jissai** [comment]
Ok, I will port my modifications on the latest code, ignore this pull request, I will try to make another cleaner tomorrow. (not quite familliar with git)

Another planned modification is to make TinyPG usable from command line for production. I saw a modification on codeproject, and i have coded one. I will see which one is the best.

Happy to see there is still life on this project, because we plan to use it a lot.

**Comment by tomspilman** [comment]
> not quite familliar with git

Yea...  I've been using it for a year and still don't feel fully comfortable with it, but it gets better.

> make TinyPG usable from command line for production

I actually added an issue the other day to remind me to add that feature:  https://github.com/SickheadGames/TinyPG/issues/3

I'd be glad to see a pull request that adds a new command line project for it.

> Happy to see there is still life on this project, because
> we plan to use it a lot.

That is why we forked it.... we love it, are using it a lot, and want to see it improve.

**Pull request closed without merging**
